import { chromium } from 'playwright';
import path from 'path';
import sharp from 'sharp';
const file = path.resolve('diagnostics/wenxin/2026-08-28_17-12-03/page/finished.html');
const browser = await chromium.launch({ channel: 'chrome', headless: false });
const page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
await page.goto('file://' + file, { waitUntil: 'domcontentloaded', timeout: 15000 });
await page.waitForTimeout(400);
const t0 = Date.now();
await page.screenshot({ path: '_full2.png', fullPage: true, animations: 'disabled' });
const box = await page.evaluate(() => { const el = document.querySelector('.chat-qa-container, [class*="chat-qa-container"]'); const r = el.getBoundingClientRect(); return { x: r.x, y: r.y, w: r.width, h: r.height }; });
const coreEnd = await page.evaluate(() => { const c = document.querySelector('.chat-search-answer-generate'); return c ? c.getBoundingClientRect().bottom : null; });
console.log('box:', JSON.stringify(box), 'coreEndY:', coreEnd);
const cropH = Math.floor((coreEnd - 6) - box.y);
console.log('cropH:', cropH);
await sharp('_full2.png').extract({ left: Math.floor(box.x), top: Math.floor(box.y), width: Math.ceil(box.w), height: cropH }).png().toFile('_full2_crop.png');
console.log('seconds:', ((Date.now()-t0)/1000).toFixed(1));
const m = await sharp('_full2_crop.png').metadata();
console.log('final:', m.width, 'x', m.height);
await browser.close();
